### ISSUE TITLE
`Too many open files` error when opening and closing socket too frequently

### ISSUE THREAD

**Issue by lyskov** [zeromq/cppzmq#257]
I noticed that if i try to open/close ZeroMQ socket too frequently then it leads to zmq::error_t: Too many open files error. Why this happening and how can i fix this?

I do understand that i can increase upper limit of available sockets but this does not sounds like good solution to me because its only delay the error. After all: i _do deallocate_ resources so why i am getting this error in the first place?

Sample code to reproduce (i tested this on v4.2.4 on Mac):

```c++
zmq::context_t context;
for(;;) {
    zmq::socket_t s (context, ZMQ_DEALER);
}
```

**Comment by sigiesec** [comment]
This is nothing that could be influenced on the level of cppzmq, but is by design of libzmq. Closing of sockets happens asynchronously. You could use a socket monitor to be notified of the actual closing of the socket. However, frequently opening and closing sockets is an antipattern in libzmq usage, and performs very badly. Does your design exhibit this behaviour in production?

**Comment by lyskov** [comment]
Thank you for clarifying this @sigiesec !  I will see if i can implement `blocking` version of closing socket though monitoring functionality.

Re usage pattern: yes and no, such behavior does not occur during normal operations but it could occur during some failure recovery situations (failure unrelated to ZMQ). So it is happening only rarely (and only for a short time) so any performance degradation is acceptable for such cases.
