### ISSUE TITLE
Curve encryption possible? - Ironhouse example missing

### ISSUE THREAD

**Issue by nilsmelchert** [zeromq/cppzmq#465]
Hello,
I am working on a c++ project and I am willing to use the "ironhouse" encryption which is given in [zmqpp](https://github.com/zeromq/zmqpp/blob/develop/examples/ironhouse2.cpp) and [pyzmq](https://github.com/zeromq/pyzmq/blob/master/examples/security/ironhouse.py).

Is there a way to implement this encryption mechanism using cppzmq?

There seems to be a related issue: #409

**Comment by brettviren** [comment]
Hi @nilsmelchert 

In short: "yes, but".

The ZAP security mechanism is implemented as "just ZeroMQ programming" so one can provide an auth actor which is implemented in `cppzmq` or in other bindings.  Or one may use, in principle, an existing ZAP auth actor based on different bindings than your main app uses.

The core restriction is that the app socket internals must themself be able to connect to something that binds `inproc://zeromq.zap.01` and this transport (I believe) requires the context to be shared between the app socket and the auth actor socket.

Three months ago I started to write a companion document to the cppzmq-tour which attempts to map the original ZAP blog posts to `cppzmq`.  I have since put it on hold so it is an unfinished work-in-progress and the example code is rather attrocious but maybe it provides some use to this issue as-is.  It did not yet get to "ironhouse".

https://github.com/brettviren/cppzmq-houses

**Comment by nilsmelchert** [comment]
@brettviren Thank you for your detailed answer. I will subscribe to your repo. Thanks for you effort in advance.

Is it a valid option to use czmq within a c++ application for now? It seems well documented and has those examples available.

**Comment by nilsmelchert** [comment]
#409

**Comment by brettviren** [comment]
@nilsmelchert The trick will be in how you share the ZeroMQ context between the bindings.

I just surveyed CZMQ and cppzmq APIs.  While I see ways with both that give us the underlying `libzmq` context, I can't find any way to **set** the `libzmq` context into a binding-level context object.  I think this sharing is required so that a cppzmq socket internals may connect to the CZMQ `zauth` over `inproc://`.

Assuming I'm not simply missing a context "setter" method in either API, I think a solution is to add to cppzmq a new constructor:

``` c++
context_t(void* libzmq_context) : ptr(libzmq_context) {}
```
This would let your app have code like:

``` c++
zctx_t* czmq_ctx = ztx_new();
zmq::context_t cppzmq_ctx(zctx_underlying(czmq_ctx));
```

You can then use the `cppzmq_ctx` to create cppzmq sockets which will be able to connect to the CZMQ `zauth` over the`inproc://zeromq.zap.01` address.

I hope the cppzmq maintainers will weigh in as the above may be crazy talk.  And/or, maybe you can hack your local copy of `zmq.hpp` to try this out and make a PR if it works?!

(I don't know enough about czmqpp to comment on your last question)

**Comment by nilsmelchert** [comment]
Thank you for your response. I ended up using czmq for my application. But I will also try to continue your work using cppzmq.

I will close this issue for now. If there are any news on the implementation of the "houses", I will place a comment here again.

**Comment by Teebonne** [comment]
You might want to look at [this](http://www.evilpaul.org/wp/2017/05/02/authentication-encryption-zeromq/).
