### ISSUE TITLE
Creating a zmq::pollitem_t requires casting to void *

### ISSUE THREAD

**Issue by darrnshn** [zeromq/cppzmq#80]
Looks like `zmq::pollitem_t` is a just typedef for `zmq_pollitem_t`. Is there any plans to make `zmq::pollitem_t` a C++ class on its own? The main reason is that creating a `zmq::pollitem_t` requires casting a `zmq::socket_t` to `void *`, which attracts bugs like:

``` cpp
zmq::pollitem_t { &socket, 0, ZMQ_POLLIN, 0 }
```

Doing a Google search shows that this bug is quite common and causes a lot of confusion. It would be good if the interface to `zmq::pollitem_t` can just take a socket without casting.

**Comment by yorickdewid** [comment]
This bug seems to be caused by the `explicit` keyword that was introduced in version 4. Explicit is used when compiling with C++11, which appends the ZMQ_EXPLICIT macro. For a void pointer operator it makes sense to use use implicit casting. Therefore removing the explicit from the function directive fixes the problem

```
